output "secret_data" {
  description = "The password generated by random password and stored in secret data of GCP secret manager"
  value       = var.create_secret ? google_secret_manager_secret_version.secret_version_basic[0].secret_data : ""
}
